export const gameExampleData = {
  data: {
    summary: {
      id: "sportradar.dhbdata.79850",
      tournament: {
        id: "sportradar.dhbdata.16059",
        name: "3. Liga M\u00e4nner",
        acronym: "",
        logo: "handball-net:files/tournaments/logos/b8da2892-a790-4010-a276-4cdee6c58b0d.png",
        livestreamUrl: null,
        organization: null,
        currentRound: null,
        table: null,
        tournamentType: "League",
        ageGroup: "Men",
        tableHint:
          "Nach Abschluss der einzelnen Runden entscheidet bei Punktgleichheit der direkte Vergleich. Bei Entscheidungs- und Ausscheidungsspielen erfolgt die Wertung nach Punkten, bei Punktgleichheit entscheidet die Tordifferenz.",
        type: "TournamentSummary",
      },
      phase: {
        id: "sportradar.dhbdata.17339",
        name: "3. Liga M\u00e4nner 23/24 - Finale",
        acronym: "",
        type: "PhaseSummary",
      },
      round: {
        id: "sportradar.dhbdata.17341",
        name: "Spieltag 2",
        acronym: "2.",
        number: 2,
        startsAt: 1717113600000,
        endsAt: 1717113600000,
        current: false,
        games: null,
        type: "RoundSummary",
      },
      field: {
        id: "sportradar.dhbdata.191",
        name: "Sporthalle St\u00e4hlerwiese",
        acronym: "",
        logo: null,
        livestreamUrl: null,
        city: "Kreuztal",
        type: "FieldSummary",
      },
      homeTeam: {
        id: "sportradar.dhbdata.1611-1595",
        name: "TuS Ferndorf",
        acronym: "FER",
        logo: "handball-net:files/clubs/logos/e824c976-cb44-4ef2-8bb5-2b8f82f6df40.png",
        livestreamUrl: null,
        teamGroupId: 21311,
        club: null,
        defaultTournament: null,
        previousGame: null,
        nextGame: null,
        type: "TeamSummary",
      },
      awayTeam: {
        id: "sportradar.dhbdata.2712-1595",
        name: "MTV Braunschweig",
        acronym: "MTV",
        logo: "handball-net:files/clubs/logos/df91816c-1dc7-49e0-a52c-7e181f4c52b5.png",
        livestreamUrl: null,
        teamGroupId: 21313,
        club: null,
        defaultTournament: null,
        previousGame: null,
        nextGame: null,
        type: "TeamSummary",
      },
      refereeInfo: null,
      livestreamUrl:
        "https://sportdeutschland.tv/tus-ferndorf/3-liga-finale-tus-ferndorf-vs-mtv-braunschweig",
      customUrl: null,
      customUrlLabel: null,
      startsAt: 1718470800000,
      attendance: 1400,
      pdfUrl: "https://dhbdata.fmp.sportradar.com/match/79850/pressReport.pdf",
      tickerRef: null,
      showTime: true,
      showPresstext: false,
      state: "Post",
      extraStates: null,
      remarks: null,
      homeGoals: 27,
      awayGoals: 27,
      homeGoalsHalf: 11,
      awayGoalsHalf: 14,
      type: "GameSummary",
    },
    lineup: {
      home: [
        {
          id: "sportradar.64229",
          firstname: "Josip",
          lastname: "Eres",
          position: "RA",
          number: 3,
          goals: 5,
          penaltyGoals: 1,
          penaltyMissed: 1,
          penalties: 1,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.64228",
          firstname: "Gabriel",
          lastname: "da Rocha Viana",
          position: "LA",
          number: 6,
          goals: 2,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 1,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.10718",
          firstname: "Ante",
          lastname: "Simic",
          position: "RL",
          number: 9,
          goals: 2,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.66380",
          firstname: "Arvid",
          lastname: "Poetz",
          position: "LA",
          number: 10,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.64230",
          firstname: "Lucas",
          lastname: "Puhl",
          position: "TW",
          number: 12,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.26",
          firstname: "Mattis",
          lastname: "Michel",
          position: "KM",
          number: 17,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 2,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.17933",
          firstname: "Daniel",
          lastname: "Hideg",
          position: "RL",
          number: 18,
          goals: 3,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.69899",
          firstname: "Konstantin",
          lastname: "Kasch",
          position: "KM",
          number: 19,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.68863",
          firstname: "Jonas",
          lastname: "Wilde",
          position: "TW",
          number: 22,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.13226",
          firstname: "Nikita",
          lastname: "Pliuto",
          position: "KM",
          number: 23,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.48257",
          firstname: "Linus",
          lastname: "Michel",
          position: "RM",
          number: 24,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.14909",
          firstname: "Marvin",
          lastname: "Mundus",
          position: "RR",
          number: 25,
          goals: 5,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.9323",
          firstname: "Janko",
          lastname: "Kevic",
          position: "RM",
          number: 28,
          goals: 9,
          penaltyGoals: 3,
          penaltyMissed: 0,
          penalties: 1,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.8447",
          firstname: "Fabian",
          lastname: "Hecker",
          position: "RR",
          number: 29,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 1,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.9386",
          firstname: "Paul",
          lastname: "Schikora",
          position: "RA",
          number: 44,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.11033",
          firstname: "Valentino",
          lastname: "Duvancic",
          position: "KM",
          number: 73,
          goals: 1,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 1,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
      ],
      homeOfficials: [
        {
          id: "sportradar.64801",
          firstname: "Jannis ",
          lastname: "Michel",
          position: "OA",
          timePenalties: null,
          warnings: 0,
          disqualifications: null,
          disqualificationWithBlueCards: null,
          type: "StaffMember",
        },
        {
          id: "sportradar.68634",
          firstname: "Ceven",
          lastname: "Klatt",
          position: "OB",
          timePenalties: null,
          warnings: 1,
          disqualifications: null,
          disqualificationWithBlueCards: null,
          type: "StaffMember",
        },
        {
          id: "sportradar.64803",
          firstname: "Nina",
          lastname: "B\u00fcdenbender",
          position: "OC",
          timePenalties: null,
          warnings: 0,
          disqualifications: null,
          disqualificationWithBlueCards: null,
          type: "StaffMember",
        },
        {
          id: "sportradar.64925",
          firstname: "Klaus",
          lastname: "Hirsch",
          position: "OD",
          timePenalties: null,
          warnings: 0,
          disqualifications: null,
          disqualificationWithBlueCards: null,
          type: "StaffMember",
        },
      ],
      away: [
        {
          id: "sportradar.10592",
          firstname: "Mustafa",
          lastname: "Wendland",
          position: "TW",
          number: 1,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.64362",
          firstname: " Nikolaos",
          lastname: "Tzoufras",
          position: "KM",
          number: 3,
          goals: 4,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.42644",
          firstname: "Jan-Bennet",
          lastname: "Kanning",
          position: "RA",
          number: 4,
          goals: 5,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 1,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.36272",
          firstname: "Bela",
          lastname: "Pieles",
          position: "LA",
          number: 5,
          goals: 7,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.7865",
          firstname: "Lukas",
          lastname: "Friedhoff",
          position: "RL",
          number: 6,
          goals: 1,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 1,
          yellowCards: 1,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.61093",
          firstname: "Jan",
          lastname: "Mudrow",
          position: "RL",
          number: 7,
          goals: 4,
          penaltyGoals: 1,
          penaltyMissed: 0,
          penalties: 1,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.68579",
          firstname: "Tim Janos",
          lastname: "Otto",
          position: "RL",
          number: 9,
          goals: 2,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.36266",
          firstname: "Niklas",
          lastname: "M\u00fchlenbruch",
          position: "KM",
          number: 10,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.10805",
          firstname: "Julius Valentin",
          lastname: "Bausch",
          position: "RM",
          number: 11,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.59885",
          firstname: "Timon",
          lastname: "Serbest",
          position: "TW",
          number: 12,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.36284",
          firstname: "Niklas",
          lastname: "Wolters",
          position: "KM",
          number: 13,
          goals: 3,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.36263",
          firstname: "Philipp Moritz",
          lastname: "Krause",
          position: "RM",
          number: 25,
          goals: 1,
          penaltyGoals: 1,
          penaltyMissed: 3,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.29039",
          firstname: "Marek",
          lastname: "Siggelkow",
          position: "RA",
          number: 34,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.36809",
          firstname: "Niklas",
          lastname: "Mellmann",
          position: "TW",
          number: 36,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.61084",
          firstname: "Tim",
          lastname: "Lietz",
          position: "RL",
          number: 66,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
        {
          id: "sportradar.48575",
          firstname: "Mika Jon",
          lastname: "Hoyer",
          position: "LA",
          number: 77,
          goals: 0,
          penaltyGoals: 0,
          penaltyMissed: 0,
          penalties: 0,
          yellowCards: 0,
          redCards: 0,
          blueCards: null,
          type: "Player",
        },
      ],
      awayOfficials: [
        {
          id: "sportradar.52142",
          firstname: "Ariel",
          lastname: "Panzer",
          position: "OA",
          timePenalties: null,
          warnings: 0,
          disqualifications: null,
          disqualificationWithBlueCards: null,
          type: "StaffMember",
        },
        {
          id: "sportradar.32397",
          firstname: "Volker",
          lastname: "Mudrow",
          position: "OB",
          timePenalties: null,
          warnings: 0,
          disqualifications: null,
          disqualificationWithBlueCards: null,
          type: "StaffMember",
        },
        {
          id: "sportradar.10073",
          firstname: "Lukas",
          lastname: "Schieb",
          position: "OC",
          timePenalties: null,
          warnings: 0,
          disqualifications: null,
          disqualificationWithBlueCards: null,
          type: "StaffMember",
        },
        {
          id: "sportradar.69946",
          firstname: "Eike",
          lastname: "Engelbrecht",
          position: "OD",
          timePenalties: null,
          warnings: 0,
          disqualifications: null,
          disqualificationWithBlueCards: null,
          type: "StaffMember",
        },
      ],
      referees: [
        {
          id: "sportradar.3317",
          firstname: "Thomas",
          lastname: "H\u00f6rath",
          position: "Schiedsrichter (1)",
          type: "Referee",
        },
        {
          id: "sportradar.3536",
          firstname: "Timo",
          lastname: "Hofmann",
          position: "Schiedsrichter (2)",
          type: "Referee",
        },
        {
          id: "sportradar.18200",
          firstname: "Ronald",
          lastname: "Klein",
          position: "Delegierte",
          type: "Referee",
        },
        {
          id: "sportradar.46382",
          firstname: "Alexander",
          lastname: "Barth",
          position: "Zeitnehmer",
          type: "Referee",
        },
        {
          id: "sportradar.46385",
          firstname: "Dustin",
          lastname: "Otto",
          position: "Sekret\u00e4r",
          type: "Referee",
        },
      ],
    },
    events: [
      {
        id: 3276531,
        type: "StopPeriod",
        time: "60:00",
        score: "27-27",
        timestamp: 1718476898000,
        team: null,
        message: "Abpfiff",
      },
      {
        id: 3276530,
        type: "Goal",
        time: "59:47",
        score: "27-27",
        timestamp: 1718476886000,
        team: "Home",
        message: "Tor durch Daniel Hideg (18.) (TuS Ferndorf)",
      },
      {
        id: 3276529,
        type: "Goal",
        time: "59:10",
        score: "26-27",
        timestamp: 1718476848000,
        team: "Away",
        message: "Tor durch  Nikolaos Tzoufras (3.) (MTV Braunschweig)",
      },
      {
        id: 3276527,
        type: "Timeout",
        time: "58:14",
        score: "26-26",
        timestamp: 1718476730000,
        team: "Away",
        message: "Auszeit MTV Braunschweig",
      },
      {
        id: 3276521,
        type: "Goal",
        time: "58:10",
        score: "26-26",
        timestamp: 1718476720000,
        team: "Home",
        message: "Tor durch Daniel Hideg (18.) (TuS Ferndorf)",
      },
      {
        id: 3276520,
        type: "Goal",
        time: "57:31",
        score: "25-26",
        timestamp: 1718476686000,
        team: "Home",
        message: "Tor durch Ante Simic (9.) (TuS Ferndorf)",
      },
      {
        id: 3276519,
        type: "Goal",
        time: "56:46",
        score: "24-26",
        timestamp: 1718476636000,
        team: "Away",
        message: "Tor durch Jan-Bennet Kanning (4.) (MTV Braunschweig)",
      },
      {
        id: 3276518,
        type: "Goal",
        time: "55:54",
        score: "24-25",
        timestamp: 1718476587000,
        team: "Home",
        message: "Tor durch Janko Kevic (28.) (TuS Ferndorf)",
      },
      {
        id: 3276515,
        type: "Goal",
        time: "55:12",
        score: "23-25",
        timestamp: 1718476533000,
        team: "Away",
        message: "Tor durch Jan Mudrow (7.) (MTV Braunschweig)",
      },
      {
        id: 3276514,
        type: "Goal",
        time: "54:40",
        score: "23-24",
        timestamp: 1718476503000,
        team: "Home",
        message: "Tor durch Janko Kevic (28.) (TuS Ferndorf)",
      },
      {
        id: 3276509,
        type: "Goal",
        time: "53:51",
        score: "22-24",
        timestamp: 1718476395000,
        team: "Away",
        message: "Tor durch Jan-Bennet Kanning (4.) (MTV Braunschweig)",
      },
      {
        id: 3276507,
        type: "Timeout",
        time: "52:48",
        score: "22-23",
        timestamp: 1718476266000,
        team: "Away",
        message: "Auszeit MTV Braunschweig",
      },
      {
        id: 3276502,
        type: "Goal",
        time: "52:37",
        score: "22-23",
        timestamp: 1718476240000,
        team: "Home",
        message: "Tor durch Josip Eres (3.) (TuS Ferndorf)",
      },
      {
        id: 3276501,
        type: "SevenMeterGoal",
        time: "52:04",
        score: "21-23",
        timestamp: 1718476209000,
        team: "Home",
        message: "7-Meter Tor durch Josip Eres (3.) (TuS Ferndorf)",
      },
      {
        id: 3276499,
        type: "TwoMinutePenalty",
        time: "51:59",
        score: null,
        timestamp: 1718476181000,
        team: "Away",
        message:
          "Lukas Friedhoff (6.) (MTV Braunschweig) erh\u00e4lt eine 2-Minuten Strafe",
      },
      {
        id: 3276495,
        type: "Goal",
        time: "51:13",
        score: "20-23",
        timestamp: 1718476126000,
        team: "Away",
        message: "Tor durch Bela Pieles (5.) (MTV Braunschweig)",
      },
      {
        id: 3276494,
        type: "Goal",
        time: "50:36",
        score: "20-22",
        timestamp: 1718476090000,
        team: "Home",
        message: "Tor durch Marvin Mundus (25.) (TuS Ferndorf)",
      },
      {
        id: 3276489,
        type: "Timeout",
        time: "48:37",
        score: "19-22",
        timestamp: 1718475867000,
        team: "Home",
        message: "Auszeit TuS Ferndorf",
      },
      {
        id: 3276485,
        type: "Goal",
        time: "47:58",
        score: "19-22",
        timestamp: 1718475812000,
        team: "Away",
        message: "Tor durch Bela Pieles (5.) (MTV Braunschweig)",
      },
      {
        id: 3276484,
        type: "SevenMeterGoal",
        time: "47:27",
        score: "19-21",
        timestamp: 1718475781000,
        team: "Home",
        message: "7-Meter Tor durch Janko Kevic (28.) (TuS Ferndorf)",
      },
      {
        id: 3276482,
        type: "TwoMinutePenalty",
        time: "47:24",
        score: null,
        timestamp: 1718475737000,
        team: "Away",
        message:
          "Jan-Bennet Kanning (4.) (MTV Braunschweig) erh\u00e4lt eine 2-Minuten Strafe",
      },
      {
        id: 3276477,
        type: "TwoMinutePenalty",
        time: "46:34",
        score: null,
        timestamp: 1718475656000,
        team: "Home",
        message:
          "Josip Eres (3.) (TuS Ferndorf) erh\u00e4lt eine 2-Minuten Strafe",
      },
      {
        id: 3276468,
        type: "Goal",
        time: "45:49",
        score: "18-21",
        timestamp: 1718475581000,
        team: "Home",
        message: "Tor durch Josip Eres (3.) (TuS Ferndorf)",
      },
      {
        id: 3276466,
        type: "TwoMinutePenalty",
        time: "45:34",
        score: null,
        timestamp: 1718475518000,
        team: "Away",
        message:
          "Jan Mudrow (7.) (MTV Braunschweig) erh\u00e4lt eine 2-Minuten Strafe",
      },
      {
        id: 3276458,
        type: "Goal",
        time: "44:39",
        score: "17-21",
        timestamp: 1718475412000,
        team: "Away",
        message: "Tor durch Bela Pieles (5.) (MTV Braunschweig)",
      },
      {
        id: 3276457,
        type: "Goal",
        time: "43:50",
        score: "17-20",
        timestamp: 1718475365000,
        team: "Away",
        message: "Tor durch Niklas Wolters (13.) (MTV Braunschweig)",
      },
      {
        id: 3276456,
        type: "Goal",
        time: "43:20",
        score: "17-19",
        timestamp: 1718475334000,
        team: "Home",
        message: "Tor durch Josip Eres (3.) (TuS Ferndorf)",
      },
      {
        id: 3276455,
        type: "SevenMeterGoal",
        time: "42:45",
        score: "16-19",
        timestamp: 1718475300000,
        team: "Away",
        message: "7-Meter Tor durch Jan Mudrow (7.) (MTV Braunschweig)",
      },
      {
        id: 3276453,
        type: "TwoMinutePenalty",
        time: "42:41",
        score: null,
        timestamp: 1718475249000,
        team: "Home",
        message:
          "Mattis Michel (17.) (TuS Ferndorf) erh\u00e4lt eine 2-Minuten Strafe",
      },
      {
        id: 3276447,
        type: "Goal",
        time: "42:04",
        score: "16-18",
        timestamp: 1718475206000,
        team: "Home",
        message: "Tor durch Janko Kevic (28.) (TuS Ferndorf)",
      },
      {
        id: 3276446,
        type: "Goal",
        time: "41:05",
        score: "15-18",
        timestamp: 1718475145000,
        team: "Away",
        message: "Tor durch Jan Mudrow (7.) (MTV Braunschweig)",
      },
      {
        id: 3276445,
        type: "SevenMeterMissed",
        time: "39:55",
        score: "15-17",
        timestamp: 1718475073000,
        team: "Away",
        message:
          "7-Meter verworfen durch Philipp Moritz Krause (25.) (MTV Braunschweig)",
      },
      {
        id: 3276440,
        type: "SevenMeterGoal",
        time: "39:09",
        score: "15-17",
        timestamp: 1718474986000,
        team: "Home",
        message: "7-Meter Tor durch Janko Kevic (28.) (TuS Ferndorf)",
      },
      {
        id: 3276431,
        type: "Goal",
        time: "35:41",
        score: "14-17",
        timestamp: 1718474704000,
        team: "Home",
        message: "Tor durch Marvin Mundus (25.) (TuS Ferndorf)",
      },
      {
        id: 3276430,
        type: "Goal",
        time: "35:10",
        score: "13-17",
        timestamp: 1718474672000,
        team: "Away",
        message: "Tor durch Bela Pieles (5.) (MTV Braunschweig)",
      },
      {
        id: 3276424,
        type: "Warning",
        time: "33:38",
        score: null,
        timestamp: 1718474553000,
        team: "Home",
        message: "Ceven Klatt (TuS Ferndorf) wurde verwarnt",
      },
      {
        id: 3276423,
        type: "Goal",
        time: "33:38",
        score: "13-16",
        timestamp: 1718474542000,
        team: "Home",
        message: "Tor durch Valentino Duvancic (73.) (TuS Ferndorf)",
      },
      {
        id: 3276421,
        type: "Goal",
        time: "33:18",
        score: "12-16",
        timestamp: 1718474522000,
        team: "Away",
        message: "Tor durch  Nikolaos Tzoufras (3.) (MTV Braunschweig)",
      },
      {
        id: 3276420,
        type: "Goal",
        time: "31:54",
        score: "12-15",
        timestamp: 1718474438000,
        team: "Away",
        message: "Tor durch  Nikolaos Tzoufras (3.) (MTV Braunschweig)",
      },
      {
        id: 3276419,
        type: "Goal",
        time: "31:01",
        score: "12-14",
        timestamp: 1718474384000,
        team: "Home",
        message: "Tor durch Marvin Mundus (25.) (TuS Ferndorf)",
      },
      {
        id: 3276416,
        type: "StartPeriod",
        time: "30:00",
        score: null,
        timestamp: 1718474300000,
        team: null,
        message: "Anpfiff",
      },
      {
        id: 3276415,
        type: "StopPeriod",
        time: "30:00",
        score: "11-14",
        timestamp: 1718473454000,
        team: null,
        message: "Abpfiff",
      },
      {
        id: 3276414,
        type: "SevenMeterMissed",
        time: "28:59",
        score: "11-14",
        timestamp: 1718473395000,
        team: "Away",
        message:
          "7-Meter verworfen durch Philipp Moritz Krause (25.) (MTV Braunschweig)",
      },
      {
        id: 3276412,
        type: "TwoMinutePenalty",
        time: "28:55",
        score: null,
        timestamp: 1718473362000,
        team: "Home",
        message:
          "Fabian Hecker (29.) (TuS Ferndorf) erh\u00e4lt eine 2-Minuten Strafe",
      },
      {
        id: 3276408,
        type: "Goal",
        time: "28:23",
        score: "11-14",
        timestamp: 1718473316000,
        team: "Home",
        message: "Tor durch Ante Simic (9.) (TuS Ferndorf)",
      },
      {
        id: 3276406,
        type: "TwoMinutePenalty",
        time: "27:27",
        score: null,
        timestamp: 1718473232000,
        team: "Home",
        message:
          "Janko Kevic (28.) (TuS Ferndorf) erh\u00e4lt eine 2-Minuten Strafe",
      },
      {
        id: 3276401,
        type: "Goal",
        time: "27:26",
        score: "10-14",
        timestamp: 1718473221000,
        team: "Away",
        message: "Tor durch Tim Janos Otto (9.) (MTV Braunschweig)",
      },
      {
        id: 3276398,
        type: "Timeout",
        time: "27:06",
        score: "10-13",
        timestamp: 1718473132000,
        team: "Away",
        message: "Auszeit MTV Braunschweig",
      },
      {
        id: 3276392,
        type: "Goal",
        time: "27:00",
        score: "10-13",
        timestamp: 1718473112000,
        team: "Home",
        message: "Tor durch Gabriel da Rocha Viana (6.) (TuS Ferndorf)",
      },
      {
        id: 3276389,
        type: "Goal",
        time: "25:54",
        score: "9-13",
        timestamp: 1718473009000,
        team: "Home",
        message: "Tor durch Janko Kevic (28.) (TuS Ferndorf)",
      },
      {
        id: 3276385,
        type: "SevenMeterGoal",
        time: "24:56",
        score: "8-13",
        timestamp: 1718472925000,
        team: "Home",
        message: "7-Meter Tor durch Janko Kevic (28.) (TuS Ferndorf)",
      },
      {
        id: 3276382,
        type: "Goal",
        time: "24:05",
        score: "7-13",
        timestamp: 1718472842000,
        team: "Away",
        message: "Tor durch Bela Pieles (5.) (MTV Braunschweig)",
      },
      {
        id: 3276381,
        type: "Goal",
        time: "23:39",
        score: "7-12",
        timestamp: 1718472817000,
        team: "Home",
        message: "Tor durch Janko Kevic (28.) (TuS Ferndorf)",
      },
      {
        id: 3276377,
        type: "TwoMinutePenalty",
        time: "21:59",
        score: null,
        timestamp: 1718472668000,
        team: "Home",
        message:
          "Mattis Michel (17.) (TuS Ferndorf) erh\u00e4lt eine 2-Minuten Strafe",
      },
      {
        id: 3276373,
        type: "TwoMinutePenalty",
        time: "21:22",
        score: null,
        timestamp: 1718472605000,
        team: "Home",
        message:
          "Valentino Duvancic (73.) (TuS Ferndorf) erh\u00e4lt eine 2-Minuten Strafe",
      },
      {
        id: 3276370,
        type: "Goal",
        time: "21:22",
        score: "6-12",
        timestamp: 1718472597000,
        team: "Away",
        message: "Tor durch Niklas Wolters (13.) (MTV Braunschweig)",
      },
      {
        id: 3276368,
        type: "SevenMeterMissed",
        time: "19:51",
        score: "6-11",
        timestamp: 1718472504000,
        team: "Away",
        message:
          "7-Meter verworfen durch Philipp Moritz Krause (25.) (MTV Braunschweig)",
      },
      {
        id: 3276362,
        type: "Goal",
        time: "18:25",
        score: "6-11",
        timestamp: 1718472360000,
        team: "Away",
        message: "Tor durch Jan-Bennet Kanning (4.) (MTV Braunschweig)",
      },
      {
        id: 3276361,
        type: "Goal",
        time: "17:42",
        score: "6-10",
        timestamp: 1718472318000,
        team: "Home",
        message: "Tor durch Daniel Hideg (18.) (TuS Ferndorf)",
      },
      {
        id: 3276356,
        type: "Goal",
        time: "15:00",
        score: "5-10",
        timestamp: 1718472124000,
        team: "Home",
        message: "Tor durch Josip Eres (3.) (TuS Ferndorf)",
      },
      {
        id: 3276355,
        type: "SevenMeterMissed",
        time: "14:21",
        score: "4-10",
        timestamp: 1718472085000,
        team: "Home",
        message: "7-Meter verworfen durch Josip Eres (3.) (TuS Ferndorf)",
      },
      {
        id: 3276347,
        type: "Warning",
        time: "12:52",
        score: null,
        timestamp: 1718471941000,
        team: "Away",
        message: "Lukas Friedhoff (6.) (MTV Braunschweig) wurde verwarnt",
      },
      {
        id: 3276346,
        type: "SevenMeterGoal",
        time: "11:26",
        score: "4-10",
        timestamp: 1718471855000,
        team: "Away",
        message:
          "7-Meter Tor durch Philipp Moritz Krause (25.) (MTV Braunschweig)",
      },
      {
        id: 3276344,
        type: "TwoMinutePenalty",
        time: "11:23",
        score: null,
        timestamp: 1718471825000,
        team: "Home",
        message:
          "Gabriel da Rocha Viana (6.) (TuS Ferndorf) erh\u00e4lt eine 2-Minuten Strafe",
      },
      {
        id: 3276338,
        type: "Goal",
        time: "10:10",
        score: "4-9",
        timestamp: 1718471730000,
        team: "Away",
        message: "Tor durch Lukas Friedhoff (6.) (MTV Braunschweig)",
      },
      {
        id: 3276337,
        type: "Goal",
        time: "09:10",
        score: "4-8",
        timestamp: 1718471672000,
        team: "Home",
        message: "Tor durch Janko Kevic (28.) (TuS Ferndorf)",
      },
      {
        id: 3276336,
        type: "Goal",
        time: "08:19",
        score: "3-8",
        timestamp: 1718471620000,
        team: "Away",
        message: "Tor durch Jan Mudrow (7.) (MTV Braunschweig)",
      },
      {
        id: 3276333,
        type: "Goal",
        time: "07:09",
        score: "3-7",
        timestamp: 1718471533000,
        team: "Away",
        message: "Tor durch Jan-Bennet Kanning (4.) (MTV Braunschweig)",
      },
      {
        id: 3276332,
        type: "Goal",
        time: "06:32",
        score: "3-6",
        timestamp: 1718471497000,
        team: "Home",
        message: "Tor durch Marvin Mundus (25.) (TuS Ferndorf)",
      },
      {
        id: 3276330,
        type: "Timeout",
        time: "06:27",
        score: "2-6",
        timestamp: 1718471410000,
        team: "Home",
        message: "Auszeit TuS Ferndorf",
      },
      {
        id: 3276325,
        type: "Goal",
        time: "05:52",
        score: "2-6",
        timestamp: 1718471365000,
        team: "Away",
        message: "Tor durch Jan-Bennet Kanning (4.) (MTV Braunschweig)",
      },
      {
        id: 3276324,
        type: "Goal",
        time: "05:36",
        score: "2-5",
        timestamp: 1718471350000,
        team: "Away",
        message: "Tor durch  Nikolaos Tzoufras (3.) (MTV Braunschweig)",
      },
      {
        id: 3276323,
        type: "Goal",
        time: "04:59",
        score: "2-4",
        timestamp: 1718471313000,
        team: "Home",
        message: "Tor durch Gabriel da Rocha Viana (6.) (TuS Ferndorf)",
      },
      {
        id: 3276322,
        type: "Goal",
        time: "04:10",
        score: "1-4",
        timestamp: 1718471264000,
        team: "Away",
        message: "Tor durch Tim Janos Otto (9.) (MTV Braunschweig)",
      },
      {
        id: 3276321,
        type: "Goal",
        time: "02:48",
        score: "1-3",
        timestamp: 1718471184000,
        team: "Away",
        message: "Tor durch Niklas Wolters (13.) (MTV Braunschweig)",
      },
      {
        id: 3276320,
        type: "Goal",
        time: "02:07",
        score: "1-2",
        timestamp: 1718471141000,
        team: "Home",
        message: "Tor durch Marvin Mundus (25.) (TuS Ferndorf)",
      },
      {
        id: 3276319,
        type: "Goal",
        time: "01:37",
        score: "0-2",
        timestamp: 1718471110000,
        team: "Away",
        message: "Tor durch Bela Pieles (5.) (MTV Braunschweig)",
      },
      {
        id: 3276318,
        type: "Goal",
        time: "00:53",
        score: "0-1",
        timestamp: 1718471068000,
        team: "Away",
        message: "Tor durch Bela Pieles (5.) (MTV Braunschweig)",
      },
      {
        id: 3276317,
        type: "StartPeriod",
        time: "00:00",
        score: null,
        timestamp: 1718471012000,
        team: null,
        message: "Anpfiff",
      },
    ],
  },
};
